config/routes.rb
Marketplace::Application.routes.draw do

  root :to => 'items#index'

  get '/items/:id/assign', :to => 'items#assign', :as => 'assign_item'

  resources :buyers do
    resources :stocks do
    end
  end

  resources :items do
    resources :reviews do
    end
    resources :reviews do
    end
  end

end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  buyer_id   :integer
#  item_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ActiveRecord::Base
  attr_accessible :buyer_id, :item_id

  belongs_to :buyer
  belongs_to :item

  def assign_to_buyer(buyer_id)
    self.update_attribute(:buyer_id, buyer_id)
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stocks }
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.json
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render json: @stock, status: :created, location: @stock }
      else
        format.html { render action: "new" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.json
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.haml
= form_for @stock do |f|
  - if @stock.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stock.errors.count, "error")} prohibited this stock from being saved:"
      %ul
        - @stock.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/stocks/edit.html.haml
%h1 Editing stock

= render 'form'

= link_to 'Show', @stock
\|
= link_to 'Back', stocks_path

app/views/stocks/index.html.haml
%h1 Listing stocks

%table
  %tr
    %th
    %th
    %th

  - @stocks.each do |stock|
    %tr
      %td= link_to 'Show', stock
      %td= link_to 'Edit', edit_stock_path(stock)
      %td= link_to 'Destroy', stock, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Stock', new_stock_path

app/views/stocks/new.html.haml
%h1 New stock

= render 'form'

= link_to 'Back', stocks_path

app/views/stocks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_stock_path(@stock)
\|
= link_to 'Back', stocks_path