config/routes.rb
Marketplace::Application.routes.draw do

  root :to => 'items#index'

  get '/items/:id/assign', :to => 'items#assign', :as => 'assign_item'

  resources :buyers do
    resources :stocks do
    end
  end

  resources :items do
    resources :reviews do
    end
    resources :reviews do
    end
  end

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  image_url   :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Item < ActiveRecord::Base
  attr_accessible :description, :name, :image_url

  has_many :reviews
  has_many :stocks
  has_many :buyers, :through => :stocks

  def not_in_stock?
    Stock.where(:item_id => self.id, :buyer_id => nil).empty?
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    if @item.not_in_stock?
      @status = "Out of Stock! Notify me when back in stock!"
    else
      @status = "In Stock! Buy Now!"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end


  def assign
    @item = Item.find(params[:id])
    @buyer = Buyer.all[0]
    if @item.not_in_stock?
      redirect_to root_path
    else
      @selected_stock = @item.stocks.where(:buyer_id => nil)[0]
      puts "before: #{@selected_stock.buyer_id}"
      @selected_stock.assign_to_buyer(@buyer.id)
      puts "after: #{@selected_stock.buyer_id}"
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/items/assign.js.haml
$('.not_in_stock').text('Purchased!')

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h3 At the market...

- @items.each do |item|
  .item{:id => "#{item.id}"}
    = link_to item_path(item.id) do
      = image_tag "#{item.image_url}"

%table
  %tr
    %th
    %th
    %th

  - @items.each do |item|
    %tr
      %td= link_to 'Show', item
      %td= link_to 'Edit', edit_item_path(item)
      %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }


%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%h3= @item.name

= image_tag "#{@item.image_url}"

%div.not_in_stock= link_to @status, assign_item_path(@item.id), :remote => true

%p= @item.description


= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path