config/routes.rb
Marketplace::Application.routes.draw do

  root :to => 'items#index'

  get '/items/:id/assign', :to => 'items#assign', :as => 'assign_item'

  resources :buyers do
    resources :stocks do
    end
  end

  resources :items do
    resources :reviews do
    end
    resources :reviews do
    end
  end

end

app/models/buyer.rb
# == Schema Information
#
# Table name: buyers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Buyer < ActiveRecord::Base
  attr_accessible :name

  has_many :stocks
  has_many :reviews
  has_many :items, :through => :stocks

end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buyers }
    end
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
    @buyer = Buyer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buyer }
    end
  end

  # GET /buyers/new
  # GET /buyers/new.json
  def new
    @buyer = Buyer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buyer }
    end
  end

  # GET /buyers/1/edit
  def edit
    @buyer = Buyer.find(params[:id])
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(params[:buyer])

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render json: @buyer, status: :created, location: @buyer }
      else
        format.html { render action: "new" }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buyers/1
  # PUT /buyers/1.json
  def update
    @buyer = Buyer.find(params[:id])

    respond_to do |format|
      if @buyer.update_attributes(params[:buyer])
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer = Buyer.find(params[:id])
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.haml
= form_for @buyer do |f|
  - if @buyer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@buyer.errors.count, "error")} prohibited this buyer from being saved:"
      %ul
        - @buyer.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/buyers/edit.html.haml
%h1 Editing buyer

= render 'form'

= link_to 'Show', @buyer
\|
= link_to 'Back', buyers_path

app/views/buyers/index.html.haml
%h1 Listing buyers

%table
  %tr
    %th
    %th
    %th

  - @buyers.each do |buyer|
    %tr
      %td= link_to 'Show', buyer
      %td= link_to 'Edit', edit_buyer_path(buyer)
      %td= link_to 'Destroy', buyer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Buyer', new_buyer_path

app/views/buyers/new.html.haml
%h1 New buyer

= render 'form'

= link_to 'Back', buyers_path

app/views/buyers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_buyer_path(@buyer)
\|
= link_to 'Back', buyers_path